# syntax version.
version: "3.7"

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:1.16.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/conf.d
      - ../chinese_chess/:/app/chinese_chess
    restart: always
    networks:
      - frontend
      - backend

  mysql:
    container_name: mysql
    image: mysql:5.7.38
    ports:
      - ${MYSQL_EXPOSE_PORT}:3306
    environment:
      TZ: ${TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
